import Head from 'next/head'

// components
import Features from '@/components/Features'
import Cotizador from '@/components/Cotizador'
import Presentation from '@/components/Presentation'

// Styles
import styles from '@/styles/components/home/hero.module.scss'
import Slogan from '@/components/Slogan'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Cotizaya | inicio</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Slogan />

      <div className="container">
        <div className={styles.hero}>
          <div className={styles.hero_flex}>
            <Cotizador />
            <Presentation />
          </div>
        </div>
        <Features />
      </div>
    </div>
  )
}

export default Home
