import { useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'

// terceros
import SwiperCore, { Navigation } from 'swiper'
import { Swiper, SwiperSlide } from 'swiper/react'

// utils
import Home from '@/svg/Home'
import Whatsapp from '@/svg/Whatsapp'
import useParams from '@/hooks/useParams'
import ChevronRight from '@/svg/ChevronRight'
import { useBreakPoint } from '@/hooks/useBreakPoint'

// styles
import styles from '@/styles/components/proveedores/proveedores.module.scss'
import Slogan from '@/components/Slogan'
import Store from '@/svg/Store'

SwiperCore.use([Navigation])

const Proveedores = () => {
  const [nroCategorias, setNroCategorias] = useState(5)
  const { nroSlides } = useBreakPoint({ sm: 1, md: 1, lg: 2, xl: 3 })
  const { params } = useParams({
    motor: '',
    marca: '',
    modelo: ''
  })

  const handleMore = () => setNroCategorias((c) => c + 1)

  const categorias = Array(nroCategorias).fill(null)

  return (
    <div>
      <Head>
        <title>Cotizaya | Proveedores</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Slogan />

      <div className={styles.proveedores}>
        <h3 className={styles.proveedores_slogan}>
          AQUÍ ESTÁN TODAS LAS TIENDAS DE REPUESTOS PARA EL {params.marca}{' '}
          {params.modelo}
        </h3>

        <div className={styles.proveedores_bread}>
          <Link href="/">
            <a>INICIO</a>
          </Link>
          <ChevronRight />
          {/* {logo} */}
          <a href="#"><img src="/images/volkswagen.jpg" alt="" /></a>
          <ChevronRight />
          <a href="#">{params.marca} {params.modelo}</a>
          <ChevronRight />
          <a href="#">Listado de tiendas</a>
        </div>

        {/* eslint-disable */}
        <>
          {/* Resultados para mobile */}
          {categorias.map((_, i) => (
            <div
              key={`categoria-${i}`}
              className={styles.proveedores_categoria}
            >
              <div className={styles.proveedores_categoriainfo}>
                <div>
                  <h3>Reparo de motor</h3>

                  <p>para {params.modelo}</p>
                </div>

                <img
                  alt=""  
                  src="https://cdn.motordoctor.de/thumb/assets/bvs/ersatz_categories/300x300/67.png"
                />
              </div>
              <div className={styles.proveedores_categoriaslider}>
                <Swiper spaceBetween={20} slidesPerView={5} navigation>
                  {Array(10)
                    .fill(null)
                    .map((_, i) => (
                      <SwiperSlide key={`proveedores-${i}`}>
                        <div className={styles.proveedores_slideritem}>
                          <img src="/images/tienda.jpg" alt="" />

                          <div>
                            <button className="btn">
                            <Store />
                              <span>Ver tienda</span>
                            </button>
                            {/* <button className="btn btn-primary">
                              <Whatsapp />
                              <span>Escríbele</span>
                            </button> */}
                          </div>
                        </div>
                      </SwiperSlide>
                    ))}
                </Swiper>

                <button style={{ marginTop: '5rem' }}  className="btn btn-secundary">Ver mas</button>
              </div>
            </div>
          ))}
        </>
        <>
          {/* Resultados para desk */}
          {[].map((_, i) => (
            <div className={styles.proveedores_grid} key={`categoria-${i}`}>
              <div className={styles.proveedores_categoria}>
                <div>
                  <h3>Reparo de motor</h3>

                  <p>
                    para {params.marca} {params.modelo}
                  </p>
                </div>

                <img src="/images/image1.jpg" alt="" />
              </div>
              {Array(8)
                .fill(null)
                .map((_, i) => (
                  <SwiperSlide key={`proveedores-${i}`}>
                    <div className={styles.proveedores_slideritem}>
                      <img src="/images/tienda.jpg" alt="" />

                      <div>
                        <button className="btn btn-outline-primary">
                          <Home /> Contactar tienda
                        </button>
                        <button className="btn btn-primary">
                          <Whatsapp /> Escríbele
                        </button>
                      </div>
                    </div>
                  </SwiperSlide>
                ))}
            </div>
          ))}
        </>

        {/* eslint-enable */}

        {/* Resultados para desktop > 992px */}

        <div onClick={handleMore} className={styles.proveedores_mostrar}>
          <button className="btn btn-primary">Mostrar mas</button>
        </div>
      </div>
    </div>
  )
}

export default Proveedores
