import { useEffect, useState } from 'react'
import Head from 'next/head'
import Link from 'next/link'
import { useRouter } from 'next/router'

// terceros
import SwiperCore, { Navigation } from 'swiper'
import { Swiper, SwiperSlide } from 'swiper/react'

// components
import Slogan from '@/components/Slogan'

// utils
import Store from '@/svg/Store'
import useParams from '@/hooks/useParams'
import ChevronRight from '@/svg/ChevronRight'
import { useBreakPoint } from '@/hooks/useBreakPoint'

import { useGetBusquedaAvanzadaQuery } from '../generated/graphql'

// styles
import styles from '@/styles/components/proveedores/proveedores.module.scss'
import Empty from '../components/Empty'
import { formatParams } from 'src/utils/formatParams'

SwiperCore.use([Navigation])

// const initialData = {
//   GetBusquedaAvanzada: {
//     data: [],
//     nroTotalItems: 0
//   }
// }

const Proveedores = () => {
  const router = useRouter()
  const [cats, setCats] = useState([])
  const { nroSlides } = useBreakPoint({ xs: 2, sm: 2, md: 2, lg: 3, xl: 5 })
  const { params } = useParams({
    motor: '',
    marca: '',
    modelo: ''
  })

  const [variables, setVariables] = useState({
    page: 1,
    numberPaginate: 10,
    volkswagen: null,
    mercedes: null,
    c17210od: null,
    of1722: null,
    of1721: null,
    cummins: null,
    om366: null,
    om906: null,
    om924: null,
    categoriaId: null
  })

  useGetBusquedaAvanzadaQuery({
    variables,
    onCompleted: (data) => {
      if (data) {
        const { GetBusquedaAvanzada, GetAllCategorias } = data
        const categorias = [...GetAllCategorias].reduce((prev, cat) => {
          const tienda = GetBusquedaAvanzada.data.filter(({ Categorias }) => {
            return Categorias.some(({ categoriaId }) => {
              return categoriaId === cat.categoriaId
            })
          })

          if (tienda.length === 0) {
            return [...prev]
          } else {
            return [...prev, { ...cat, tienda }]
          }
        }, [])

        // console.log('RESULT', categorias)
        setCats(categorias)
      }
    }
  })

  useEffect(() => {
    const paramsFormated = formatParams(params)
    setVariables(paramsFormated)
  }, [params])

  const handleDetailStore = (tienda) => {
    router.push({
      pathname: '/detalle-tienda',
      query: {
        ...params,
        tienda
      }
    })
  }

  const brandLogo = (brand) => {
    if (brand === 'Volkswagen') return '/images/volkswagen.jpg'
    if (brand === 'Mercedes Benz') return '/images/mercedes.png'
  }

  return (
    <div>
      <Head>
        <title>Cotizaya | Proveedores</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Slogan />

      <div className={styles.proveedores}>
        <h3 className={styles.proveedores_slogan}>
          AQUÍ ESTÁN TODAS LAS TIENDAS DE REPUESTOS PARA EL {params.marca}{' '}
          {params.modelo}
        </h3>

        <div className={styles.proveedores_bread}>
          <div>
            <Link href="/">
              <a>INICIO</a>
            </Link>
            <ChevronRight />
            {/* {logo} */}
            <a href="#">
              <img src={brandLogo(params.marca)} alt="" />
            </a>
            <ChevronRight />
            <a href="#">
              {params.marca} {params.modelo}
            </a>
            <ChevronRight />
            <a href="#">Listado de tiendas</a>
          </div>
        </div>

        {cats.map((cat, i) => (
          <div
            key={`categoria-${cat.categoriaId}`}
            className={styles.proveedores_categoria}
          >
            <div className={styles.proveedores_categoriainfo}>
              {/* START TITULO EN DESKTOP */}
              <div>
                <h3>{cat.titulo}</h3>
                <p>para {params.modelo}</p>
              </div>
              {/* END TITULO EN DESKTOP */}

              <img alt="" src={cat.imagenPrincipal.url} />
            </div>
            <div className={styles.proveedores_categoriaslider}>
              {/* START TITULO EN MOBILE */}
              <div>
                <h3>{cat.titulo}</h3>
                <p>para {params.modelo}</p>
              </div>
              {/* END TITULO EN MOBILE */}

              <div className={styles.slider_mobile}>
                {cat.tienda.map((tienda, i) => (
                  <div
                    key={`proveedores-${tienda.tiendaId}`}
                    className={styles.proveedores_slideritem}
                  >
                    <div>
                      <img
                        src={
                          tienda.imagenPrincipal.id
                            ? tienda.imagenPrincipal.url
                            : '/images/tienda.jpg'
                        }
                        alt=""
                      />
                    </div>
                    <div>
                      <button
                        onClick={() => handleDetailStore(tienda.slug)}
                        className="btn"
                      >
                        <Store />
                        <span>Ver tienda</span>
                      </button>
                    </div>
                  </div>
                ))}
              </div>

              <div className={styles.slider_desktop}>
                <Swiper
                  // width={350}
                  spaceBetween={20}
                  slidesPerView={nroSlides}
                  navigation
                >
                  {cat.tienda.map((tienda, i) => (
                    <SwiperSlide key={`proveedores-${tienda.tiendaId}`}>
                      <div className={styles.proveedores_slideritem}>
                        <div>
                          <img
                            src={
                              tienda.imagenPrincipal.id
                                ? tienda.imagenPrincipal.url
                                : '/images/tienda.jpg'
                            }
                            alt=""
                          />
                        </div>
                        <div>
                          <button
                            onClick={() => handleDetailStore(tienda.slug)}
                            className="btn"
                          >
                            <Store />
                            <span>Ver tienda</span>
                          </button>
                        </div>
                      </div>
                    </SwiperSlide>
                  ))}
                </Swiper>
              </div>

              <button
                onClick={() => {
                  router.push({
                    pathname: `/tienda/${cat.categoriaId}`,
                    query: {
                      marca: params.marca,
                      modelo: params.modelo,
                      motor: params.motor
                    }
                  })
                }}
                className="btn btn-secundary"
              >
                Ver mas
              </button>
            </div>
          </div>
        ))}

        {cats.length === 0 ? <Empty /> : null}
      </div>
    </div>
  )
}

export default Proveedores
