import Head from 'next/head'
import Link from 'next/link'
import router from 'next/router'
import { useEffect, useState } from 'react'

// utils
import Store from '@/svg/Store'
import useParams from '@/hooks/useParams'
import ChevronRight from '@/svg/ChevronRight'

// styles
import styles from '@/styles/components/tienda/tienda.module.scss'
import { useGetBusquedaAvanzadaQuery } from '../../generated/graphql'
import { formatParams } from 'src/utils/formatParams'
import { handlePagination } from 'src/utils/handlePagination'

const initialVar = {
  page: 1,
  numberPaginate: 10,
  volkswagen: null,
  mercedes: null,
  c17210od: null,
  of1722: null,
  of1721: null,
  cummins: null,
  om366: null,
  om906: null,
  om924: null,
  categoriaId: null
}

const Tienda = () => {
  const [tiendas, setTiendas] = useState({ data: [], nroTotalItems: 0 })
  const [variables, setVariables] = useState(initialVar)
  const { params } = useParams({
    id: null,
    motor: '',
    marca: '',
    modelo: ''
  })

  useGetBusquedaAvanzadaQuery({
    variables,
    onCompleted: (data) => {
      if (data) {
        const { GetBusquedaAvanzada } = data

        console.log('RESULT', GetBusquedaAvanzada)
        setTiendas(GetBusquedaAvanzada)
      }
    }
  })

  useEffect(() => {
    if (params.id) {
      const paramsFormated = formatParams(params)
      setVariables(paramsFormated)
    }
  }, [params.id])

  const brandLogo = (brand) => {
    if (brand === 'Volkswagen') return '/images/volkswagen.jpg'
    if (brand === 'Mercedes Benz') return '/images/mercedes.png'
  }

  const handleDetailStore = (tienda) => {
    router.push({
      pathname: '/detalle-tienda',
      query: {
        ...params,
        tienda
      }
    })
  }

  const handleGoBack = (payload) => {
    router.push({
      pathname: '/proveedores',
      query: {
        ...payload
      }
    })
  }

  const nroPage = handlePagination(tiendas.nroTotalItems)

  return (
    <div>
      <Head>
        <title>Cotizaya | Tiendas</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={styles.tienda}>
        <h3 className={styles.tienda_slogan}>
          AQUÍ ESTÁN TODAS LAS TIENDAS DE REPUESTOS PARA EL {params.marca}{' '}
          {params.modelo}
        </h3>

        <div className={styles.tienda_bread}>
          <div>
            <Link href="/">
              <a>INICIO</a>
            </Link>
            <ChevronRight />
            <a
              href="#"
              onClick={(e) => {
                e.preventDefault()
                const { marca } = params
                handleGoBack({ marca })
              }}
            >
              <img src={brandLogo(params.marca)} alt="" />
            </a>
            <ChevronRight />
            <a
              href="#"
              onClick={(e) => {
                e.preventDefault()
                const { id, ...rest } = params
                handleGoBack(rest)
              }}
            >
              {params.marca} {params.modelo}
            </a>
            <ChevronRight />
            <p style={{ margin: 0 }}>Listado de tiendas</p>
          </div>
        </div>

        <div className={styles.tienda_categoria}>
          <div>
            <h3>Reparo de motor</h3>
            <p>para {params.modelo}</p>
          </div>

          <div className={styles.slider_mobile}>
            {tiendas.data.map((tienda, i) => (
              <div
                key={`tiendas-${tienda.tiendaId}`}
                className={styles.tienda_slideritem}
              >
                <img
                  src={
                    tienda.imagenPrincipal.id
                      ? tienda.imagenPrincipal.url
                      : '/images/tienda.jpg'
                  }
                  alt=""
                />
                <div>
                  <button
                    onClick={() => handleDetailStore(tienda.slug)}
                    className="btn"
                  >
                    <Store />
                    <span>Ver tienda</span>
                  </button>
                </div>
              </div>
            ))}
          </div>

          <div className={styles.paginacion}>
            <span>1</span> de {nroPage}
            <a
              href="#"
              disabled={nroPage === variables.page}
              onClick={(e) => {
                e.preventDefault()
                if (nroPage === variables.page) return
                setVariables((v) => ({ ...v, page: v.page + 1 }))
              }}
            >
              Siguiente {'>'}
            </a>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Tienda
