import Head from 'next/head'
import Link from 'next/link'
import router from 'next/router'
import { useEffect, useState } from 'react'

// utils
import Store from '@/svg/Store'
import useParams from '@/hooks/useParams'
import ChevronRight from '@/svg/ChevronRight'

// styles
import styles from '@/styles/components/tienda/tienda.module.scss'
import { useGetBusquedaAvanzadaQuery } from '../../generated/graphql'

const initialVar = {
  page: 1,
  numberPaginate: 10,
  volkswagen: null,
  mercedes: null,
  c17210od: null,
  of1722: null,
  of1721: null,
  cummins: null,
  om366: null,
  om906: null,
  om924: null,
  categoriaId: null
}

const Tienda = () => {
  const [tiendas, setTiendas] = useState([])
  const [variables, setVariables] = useState(initialVar)
  const { params } = useParams({
    id: null,
    motor: '',
    marca: '',
    modelo: ''
  })

  useGetBusquedaAvanzadaQuery({
    variables,
    onCompleted: (data) => {
      if (data) {
        const { GetBusquedaAvanzada, GetAllCategorias } = data
        const categorias = [...GetAllCategorias].reduce((prev, cat) => {
          const tienda = GetBusquedaAvanzada.data.filter(({ Categorias }) => {
            return Categorias.some(({ categoriaId }) => {
              return categoriaId === cat.categoriaId
            })
          })

          if (tienda.length === 0) {
            return [...prev]
          } else {
            return [...prev, { ...cat, tienda }]
          }
        }, [])

        console.log('RESULT', categorias)
        if (categorias.length !== 0) {
          setTiendas(categorias[0].tienda)
        }
      }
    }
  })

  useEffect(() => {
    if (params.id) {
      setVariables((v) => ({ ...v, categoriaId: params.id }))
    }
  }, [params.id])

  const brandLogo = (brand) => {
    if (brand === 'Volkswagen') return '/images/volkswagen.jpg'
    if (brand === 'Mercedes Benz') return '/images/mercedes.png'
  }

  const handleDetailStore = (tienda) => {
    router.push({
      pathname: '/detalle-tienda',
      query: {
        ...params,
        tienda
      }
    })
  }

  return (
    <div>
      <Head>
        <title>Cotizaya | Tiendas</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={styles.tienda}>
        <h3 className={styles.tienda_slogan}>
          AQUÍ ESTÁN TODAS LAS TIENDAS DE REPUESTOS PARA EL {params.marca}{' '}
          {params.modelo}
        </h3>

        <div className={styles.tienda_bread}>
          <div>
            <Link href="/">
              <a>INICIO</a>
            </Link>
            <ChevronRight />
            <a href="#">
              <img src={brandLogo(params.marca)} alt="" />
            </a>
            <ChevronRight />
            <a href="#">
              {params.marca} {params.modelo}
            </a>
            <ChevronRight />
            <a href="#">Listado de tiendas</a>
          </div>
        </div>

        <div className={styles.tienda_categoria}>
          <div>
            <h3>Reparo de motor</h3>
            <p>para {params.modelo}</p>
          </div>

          <div className={styles.slider_mobile}>
            {tiendas.map((tienda, i) => (
              <div
                key={`tiendas-${tienda.tiendaId}`}
                className={styles.tienda_slideritem}
              >
                <img
                  src={
                    tienda.imagenPrincipal.id
                      ? tienda.imagenPrincipal.url
                      : '/images/tienda.jpg'
                  }
                  alt=""
                />
                <div>
                  <button
                    onClick={() => handleDetailStore(tienda.slug)}
                    className="btn"
                  >
                    <Store />
                    <span>Ver tienda</span>
                  </button>
                </div>
              </div>
            ))}
          </div>

          <div className={styles.paginacion}>
            <span>1</span> de 10 <a href="#">Siguiente {'>'}</a>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Tienda
