import Head from 'next/head'
import Link from 'next/link'
import router from 'next/router'

// utils
import Store from '@/svg/Store'
import useParams from '@/hooks/useParams'
import ChevronRight from '@/svg/ChevronRight'

// styles
import styles from '@/styles/components/tienda/tienda.module.scss'

const Tienda = () => {
  const { params } = useParams({
    motor: '',
    marca: '',
    modelo: ''
  })

  const brandLogo = (brand) => {
    if (brand === 'Volkswagen') return '/images/volkswagen.jpg'
    if (brand === 'Mercedes Benz') return '/images/mercedes.png'
  }

  const handleDetailStore = (tienda) => {
    router.push({
      pathname: '/detalle-tienda',
      query: {
        ...params,
        tienda
      }
    })
  }

  return (
    <div>
      <Head>
        <title>Cotizaya | Tiendas</title>
        <link rel="icon" href="/favicon.ico" />
        <meta name="description" content="Generated by create next app" />
      </Head>

      <div className={styles.tienda}>
        <h3 className={styles.tienda_slogan}>
          AQUÍ ESTÁN TODAS LAS TIENDAS DE REPUESTOS PARA EL {params.marca}{' '}
          {params.modelo}
        </h3>

        <div className={styles.tienda_bread}>
          <div>
            <Link href="/">
              <a>INICIO</a>
            </Link>
            <ChevronRight />
            <a href="#">
              <img src={brandLogo(params.marca)} alt="" />
            </a>
            <ChevronRight />
            <a href="#">
              {params.marca} {params.modelo}
            </a>
            <ChevronRight />
            <a href="#">Listado de tiendas</a>
          </div>
        </div>

        <div className={styles.tienda_categoria}>
          <div>
            <h3>Reparo de motor</h3>
            <p>para {params.modelo}</p>
          </div>

          <div className={styles.slider_mobile}>
            {Array(10)
              .fill(null)
              .map((_, i) => (
                <div key={`tiendas-${i}`} className={styles.tienda_slideritem}>
                  <img src="/images/tienda.jpg" alt="" />
                  <div>
                    <button onClick={() => handleDetailStore('Agepsa')} className="btn">
                      <Store />
                      <span>Ver tienda</span>
                    </button>
                  </div>
                </div>
              ))}
          </div>

          <div className={styles.paginacion}>
            <span>1</span> de 10 <a href="#">Siguiente {'>'}</a>
          </div>
        </div>
      </div>
    </div>
  )
}

export default Tienda
